[package]
name = "mean-integers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Add  math library to your dependencies
math = "0.1.0"
factorial = "0.1.0"
round = "0.1.0"